In [1]:
import torch
import numpy as np

Python List

In [2]:
list = [1,2,3,4]


list2 = [[1,2,3,4],[6,7,8,9]]
list, list2

([1, 2, 3, 4], [[1, 2, 3, 4], [6, 7, 8, 9]])

Numpy Array

In [3]:
np_array= np.random.rand(3,5)
np_array

array([[0.66780522, 0.08819506, 0.73808111, 0.31248551, 0.3064437 ],
       [0.1698033 , 0.41693128, 0.23495654, 0.50726525, 0.82182896],
       [0.91812378, 0.41105356, 0.66659893, 0.32075167, 0.74628803]])

In [4]:
np_array.dtype

dtype('float64')

Tensor

In [5]:
t_2d = torch.rand(3,4)
t_2d, t_2d.dtype

(tensor([[0.7493, 0.1957, 0.5864, 0.1393],
         [0.3932, 0.2284, 0.5300, 0.7839],
         [0.1683, 0.5686, 0.5188, 0.6850]]),
 torch.float32)

In [6]:
t_3d = torch.ones(2,3,4)
t_3d, t_3d.dtype

(tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 torch.float32)

In [7]:
np_2_tensor = torch.tensor(np_array)
np_2_tensor, np_2_tensor.dtype

(tensor([[0.6678, 0.0882, 0.7381, 0.3125, 0.3064],
         [0.1698, 0.4169, 0.2350, 0.5073, 0.8218],
         [0.9181, 0.4111, 0.6666, 0.3208, 0.7463]], dtype=torch.float64),
 torch.float64)

In [8]:
my_tensor = torch.arange(10)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
my_tensor1 = my_tensor.reshape(2,5)
my_tensor1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
my_tensor2 = torch.arange(15)
my_tensor2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
my_tensor3 = my_tensor2.reshape(3,-1)
my_tensor3

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [12]:
my_tensor4 = my_tensor3.view(3,5)
my_tensor4

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [13]:
#chech what hpen when change the values
a = torch.arange(10)
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a2 = a.reshape(2,5)
a2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
a[3] = 231

In [16]:
a2

tensor([[  0,   1,   2, 231,   4],
        [  5,   6,   7,   8,   9]])

In [17]:
a3 = a.reshape(5,2)
a3

tensor([[  0,   1],
        [  2, 231],
        [  4,   5],
        [  6,   7],
        [  8,   9]])

In [18]:
a3[:,1]

tensor([  1, 231,   5,   7,   9])

In [19]:
a3[:,1:]

tensor([[  1],
        [231],
        [  5],
        [  7],
        [  9]])

In [20]:
a = torch.tensor([1,2,3,4])
b = torch.tensor([5,6,7,8])


In [21]:
a+b

tensor([ 6,  8, 10, 12])

In [22]:
torch.add(a,b)

tensor([ 6,  8, 10, 12])

In [23]:
b-a

tensor([4, 4, 4, 4])

In [24]:
torch.sub(b,a)

tensor([4, 4, 4, 4])

In [25]:
torch.mul(a,b)

tensor([ 5, 12, 21, 32])

In [26]:
torch.div(a,b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [27]:
torch.remainder(b,a)

tensor([0, 0, 1, 0])

In [28]:
torch.pow(a,b)

tensor([    1,    64,  2187, 65536])

In [29]:
a.add(b)

tensor([ 6,  8, 10, 12])